/**
 */
package org.opcfoundation.ua._2011._03.ua.node.set.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.opcfoundation.ua._2011._03.ua.node.set.util.SetAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SetItemProviderAdapterFactory extends SetAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SetItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.AliasTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AliasTableItemProvider aliasTableItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.AliasTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAliasTableAdapter() {
		if (aliasTableItemProvider == null) {
			aliasTableItemProvider = new AliasTableItemProvider(this);
		}

		return aliasTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.DataTypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeDefinitionItemProvider dataTypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.DataTypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeDefinitionAdapter() {
		if (dataTypeDefinitionItemProvider == null) {
			dataTypeDefinitionItemProvider = new DataTypeDefinitionItemProvider(this);
		}

		return dataTypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.DataTypeField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeFieldItemProvider dataTypeFieldItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.DataTypeField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeFieldAdapter() {
		if (dataTypeFieldItemProvider == null) {
			dataTypeFieldItemProvider = new DataTypeFieldItemProvider(this);
		}

		return dataTypeFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ExtensionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensionTypeItemProvider extensionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ExtensionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtensionTypeAdapter() {
		if (extensionTypeItemProvider == null) {
			extensionTypeItemProvider = new ExtensionTypeItemProvider(this);
		}

		return extensionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ListOfExtensions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListOfExtensionsItemProvider listOfExtensionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ListOfExtensions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListOfExtensionsAdapter() {
		if (listOfExtensionsItemProvider == null) {
			listOfExtensionsItemProvider = new ListOfExtensionsItemProvider(this);
		}

		return listOfExtensionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ListOfReferences} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListOfReferencesItemProvider listOfReferencesItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ListOfReferences}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListOfReferencesAdapter() {
		if (listOfReferencesItemProvider == null) {
			listOfReferencesItemProvider = new ListOfReferencesItemProvider(this);
		}

		return listOfReferencesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ListOfRolePermissions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListOfRolePermissionsItemProvider listOfRolePermissionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ListOfRolePermissions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListOfRolePermissionsAdapter() {
		if (listOfRolePermissionsItemProvider == null) {
			listOfRolePermissionsItemProvider = new ListOfRolePermissionsItemProvider(this);
		}

		return listOfRolePermissionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.LocalizedText} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalizedTextItemProvider localizedTextItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.LocalizedText}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalizedTextAdapter() {
		if (localizedTextItemProvider == null) {
			localizedTextItemProvider = new LocalizedTextItemProvider(this);
		}

		return localizedTextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ModelTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelTableItemProvider modelTableItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ModelTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelTableAdapter() {
		if (modelTableItemProvider == null) {
			modelTableItemProvider = new ModelTableItemProvider(this);
		}

		return modelTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ModelTableEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelTableEntryItemProvider modelTableEntryItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ModelTableEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelTableEntryAdapter() {
		if (modelTableEntryItemProvider == null) {
			modelTableEntryItemProvider = new ModelTableEntryItemProvider(this);
		}

		return modelTableEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeIdAlias} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeIdAliasItemProvider nodeIdAliasItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeIdAlias}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeIdAliasAdapter() {
		if (nodeIdAliasItemProvider == null) {
			nodeIdAliasItemProvider = new NodeIdAliasItemProvider(this);
		}

		return nodeIdAliasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeSetStatus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeSetStatusItemProvider nodeSetStatusItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeSetStatus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeSetStatusAdapter() {
		if (nodeSetStatusItemProvider == null) {
			nodeSetStatusItemProvider = new NodeSetStatusItemProvider(this);
		}

		return nodeSetStatusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeSetStatusList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeSetStatusListItemProvider nodeSetStatusListItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeSetStatusList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeSetStatusListAdapter() {
		if (nodeSetStatusListItemProvider == null) {
			nodeSetStatusListItemProvider = new NodeSetStatusListItemProvider(this);
		}

		return nodeSetStatusListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.NodesToAdd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodesToAddItemProvider nodesToAddItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.NodesToAdd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodesToAddAdapter() {
		if (nodesToAddItemProvider == null) {
			nodesToAddItemProvider = new NodesToAddItemProvider(this);
		}

		return nodesToAddItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.NodesToDelete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodesToDeleteItemProvider nodesToDeleteItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.NodesToDelete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodesToDeleteAdapter() {
		if (nodesToDeleteItemProvider == null) {
			nodesToDeleteItemProvider = new NodesToDeleteItemProvider(this);
		}

		return nodesToDeleteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeToDelete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeToDeleteItemProvider nodeToDeleteItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.NodeToDelete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeToDeleteAdapter() {
		if (nodeToDeleteItemProvider == null) {
			nodeToDeleteItemProvider = new NodeToDeleteItemProvider(this);
		}

		return nodeToDeleteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.Reference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceItemProvider referenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.Reference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceAdapter() {
		if (referenceItemProvider == null) {
			referenceItemProvider = new ReferenceItemProvider(this);
		}

		return referenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ReferenceChange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceChangeItemProvider referenceChangeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ReferenceChange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceChangeAdapter() {
		if (referenceChangeItemProvider == null) {
			referenceChangeItemProvider = new ReferenceChangeItemProvider(this);
		}

		return referenceChangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ReferencesToChange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferencesToChangeItemProvider referencesToChangeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ReferencesToChange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferencesToChangeAdapter() {
		if (referencesToChangeItemProvider == null) {
			referencesToChangeItemProvider = new ReferencesToChangeItemProvider(this);
		}

		return referencesToChangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.RolePermission} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RolePermissionItemProvider rolePermissionItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.RolePermission}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRolePermissionAdapter() {
		if (rolePermissionItemProvider == null) {
			rolePermissionItemProvider = new RolePermissionItemProvider(this);
		}

		return rolePermissionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.StructureTranslationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructureTranslationTypeItemProvider structureTranslationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.StructureTranslationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructureTranslationTypeAdapter() {
		if (structureTranslationTypeItemProvider == null) {
			structureTranslationTypeItemProvider = new StructureTranslationTypeItemProvider(this);
		}

		return structureTranslationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.TranslationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TranslationTypeItemProvider translationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.TranslationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTranslationTypeAdapter() {
		if (translationTypeItemProvider == null) {
			translationTypeItemProvider = new TranslationTypeItemProvider(this);
		}

		return translationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UADataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UADataTypeItemProvider uaDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UADataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUADataTypeAdapter() {
		if (uaDataTypeItemProvider == null) {
			uaDataTypeItemProvider = new UADataTypeItemProvider(this);
		}

		return uaDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAInstanceItemProvider uaInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAInstanceAdapter() {
		if (uaInstanceItemProvider == null) {
			uaInstanceItemProvider = new UAInstanceItemProvider(this);
		}

		return uaInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAMethodItemProvider uaMethodItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAMethodAdapter() {
		if (uaMethodItemProvider == null) {
			uaMethodItemProvider = new UAMethodItemProvider(this);
		}

		return uaMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAMethodArgument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAMethodArgumentItemProvider uaMethodArgumentItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAMethodArgument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAMethodArgumentAdapter() {
		if (uaMethodArgumentItemProvider == null) {
			uaMethodArgumentItemProvider = new UAMethodArgumentItemProvider(this);
		}

		return uaMethodArgumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UANode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UANodeItemProvider uaNodeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UANode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUANodeAdapter() {
		if (uaNodeItemProvider == null) {
			uaNodeItemProvider = new UANodeItemProvider(this);
		}

		return uaNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UANodeSetChangesStatusType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UANodeSetChangesStatusTypeItemProvider uaNodeSetChangesStatusTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UANodeSetChangesStatusType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUANodeSetChangesStatusTypeAdapter() {
		if (uaNodeSetChangesStatusTypeItemProvider == null) {
			uaNodeSetChangesStatusTypeItemProvider = new UANodeSetChangesStatusTypeItemProvider(this);
		}

		return uaNodeSetChangesStatusTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UANodeSetChangesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UANodeSetChangesTypeItemProvider uaNodeSetChangesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UANodeSetChangesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUANodeSetChangesTypeAdapter() {
		if (uaNodeSetChangesTypeItemProvider == null) {
			uaNodeSetChangesTypeItemProvider = new UANodeSetChangesTypeItemProvider(this);
		}

		return uaNodeSetChangesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UANodeSetType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UANodeSetTypeItemProvider uaNodeSetTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UANodeSetType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUANodeSetTypeAdapter() {
		if (uaNodeSetTypeItemProvider == null) {
			uaNodeSetTypeItemProvider = new UANodeSetTypeItemProvider(this);
		}

		return uaNodeSetTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAObjectItemProvider uaObjectItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAObjectAdapter() {
		if (uaObjectItemProvider == null) {
			uaObjectItemProvider = new UAObjectItemProvider(this);
		}

		return uaObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAObjectType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAObjectTypeItemProvider uaObjectTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAObjectType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAObjectTypeAdapter() {
		if (uaObjectTypeItemProvider == null) {
			uaObjectTypeItemProvider = new UAObjectTypeItemProvider(this);
		}

		return uaObjectTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAReferenceType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAReferenceTypeItemProvider uaReferenceTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAReferenceType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAReferenceTypeAdapter() {
		if (uaReferenceTypeItemProvider == null) {
			uaReferenceTypeItemProvider = new UAReferenceTypeItemProvider(this);
		}

		return uaReferenceTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UATypeItemProvider uaTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUATypeAdapter() {
		if (uaTypeItemProvider == null) {
			uaTypeItemProvider = new UATypeItemProvider(this);
		}

		return uaTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAVariableItemProvider uaVariableItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAVariableAdapter() {
		if (uaVariableItemProvider == null) {
			uaVariableItemProvider = new UAVariableItemProvider(this);
		}

		return uaVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAVariableType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAVariableTypeItemProvider uaVariableTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAVariableType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAVariableTypeAdapter() {
		if (uaVariableTypeItemProvider == null) {
			uaVariableTypeItemProvider = new UAVariableTypeItemProvider(this);
		}

		return uaVariableTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UAView} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UAViewItemProvider uaViewItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UAView}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUAViewAdapter() {
		if (uaViewItemProvider == null) {
			uaViewItemProvider = new UAViewItemProvider(this);
		}

		return uaViewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.UriTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UriTableItemProvider uriTableItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.UriTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUriTableAdapter() {
		if (uriTableItemProvider == null) {
			uriTableItemProvider = new UriTableItemProvider(this);
		}

		return uriTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ValueType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueTypeItemProvider valueTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ValueType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValueTypeAdapter() {
		if (valueTypeItemProvider == null) {
			valueTypeItemProvider = new ValueTypeItemProvider(this);
		}

		return valueTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opcfoundation.ua._2011._03.ua.node.set.ValueType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueType1ItemProvider valueType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.opcfoundation.ua._2011._03.ua.node.set.ValueType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValueType1Adapter() {
		if (valueType1ItemProvider == null) {
			valueType1ItemProvider = new ValueType1ItemProvider(this);
		}

		return valueType1ItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (aliasTableItemProvider != null) aliasTableItemProvider.dispose();
		if (dataTypeDefinitionItemProvider != null) dataTypeDefinitionItemProvider.dispose();
		if (dataTypeFieldItemProvider != null) dataTypeFieldItemProvider.dispose();
		if (documentRootItemProvider != null) documentRootItemProvider.dispose();
		if (extensionTypeItemProvider != null) extensionTypeItemProvider.dispose();
		if (listOfExtensionsItemProvider != null) listOfExtensionsItemProvider.dispose();
		if (listOfReferencesItemProvider != null) listOfReferencesItemProvider.dispose();
		if (listOfRolePermissionsItemProvider != null) listOfRolePermissionsItemProvider.dispose();
		if (localizedTextItemProvider != null) localizedTextItemProvider.dispose();
		if (modelTableItemProvider != null) modelTableItemProvider.dispose();
		if (modelTableEntryItemProvider != null) modelTableEntryItemProvider.dispose();
		if (nodeIdAliasItemProvider != null) nodeIdAliasItemProvider.dispose();
		if (nodeSetStatusItemProvider != null) nodeSetStatusItemProvider.dispose();
		if (nodeSetStatusListItemProvider != null) nodeSetStatusListItemProvider.dispose();
		if (nodesToAddItemProvider != null) nodesToAddItemProvider.dispose();
		if (nodesToDeleteItemProvider != null) nodesToDeleteItemProvider.dispose();
		if (nodeToDeleteItemProvider != null) nodeToDeleteItemProvider.dispose();
		if (referenceItemProvider != null) referenceItemProvider.dispose();
		if (referenceChangeItemProvider != null) referenceChangeItemProvider.dispose();
		if (referencesToChangeItemProvider != null) referencesToChangeItemProvider.dispose();
		if (rolePermissionItemProvider != null) rolePermissionItemProvider.dispose();
		if (structureTranslationTypeItemProvider != null) structureTranslationTypeItemProvider.dispose();
		if (translationTypeItemProvider != null) translationTypeItemProvider.dispose();
		if (uaDataTypeItemProvider != null) uaDataTypeItemProvider.dispose();
		if (uaInstanceItemProvider != null) uaInstanceItemProvider.dispose();
		if (uaMethodItemProvider != null) uaMethodItemProvider.dispose();
		if (uaMethodArgumentItemProvider != null) uaMethodArgumentItemProvider.dispose();
		if (uaNodeItemProvider != null) uaNodeItemProvider.dispose();
		if (uaNodeSetChangesStatusTypeItemProvider != null) uaNodeSetChangesStatusTypeItemProvider.dispose();
		if (uaNodeSetChangesTypeItemProvider != null) uaNodeSetChangesTypeItemProvider.dispose();
		if (uaNodeSetTypeItemProvider != null) uaNodeSetTypeItemProvider.dispose();
		if (uaObjectItemProvider != null) uaObjectItemProvider.dispose();
		if (uaObjectTypeItemProvider != null) uaObjectTypeItemProvider.dispose();
		if (uaReferenceTypeItemProvider != null) uaReferenceTypeItemProvider.dispose();
		if (uaTypeItemProvider != null) uaTypeItemProvider.dispose();
		if (uaVariableItemProvider != null) uaVariableItemProvider.dispose();
		if (uaVariableTypeItemProvider != null) uaVariableTypeItemProvider.dispose();
		if (uaViewItemProvider != null) uaViewItemProvider.dispose();
		if (uriTableItemProvider != null) uriTableItemProvider.dispose();
		if (valueTypeItemProvider != null) valueTypeItemProvider.dispose();
		if (valueType1ItemProvider != null) valueType1ItemProvider.dispose();
	}

}
